# Generated by Django 3.2.9 on 2021-11-29 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cute_dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='강아지 이름')),
                ('breed', models.CharField(max_length=100, verbose_name='강아지 품종')),
                ('size', models.CharField(max_length=11, verbose_name='강아지 크기')),
            ],
        ),
    ]
