# Generated by Django 3.2.9 on 2021-12-06 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoona', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studypost',
            name='photo',
            field=models.ImageField(blank=True, upload_to='yoona/images/%Y/%M/%d/'),
        ),
        migrations.AlterField(
            model_name='studypost',
            name='studynote',
            field=models.BooleanField(verbose_name='학습일기 썼습니까?'),
        ),
    ]
