# Generated by Django 3.2.10 on 2021-12-13 02:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion

# 절대 상단에서 from shop.models. import Category를 하지 마시고
# 마이그레이션 함수 내부에서 apps를 통해 모델 클래스를 가져오세요
# 밑에처럼!!


# 카테고리 테이블이 만들어지고 나서 수행 (정방향)
def create_dummy_category(apps,schema_editor):
    Category = apps.get_model("shop","Category") # model class
    Category.objects.create(name="dummy")

# 카테고리 테이블이 삭제되고 나서 수행 (역방향)
def delete_dummy_category(apps,schema_editor):
    Category = apps.get_model("shop", "Category")  # model class
    Category.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': '리뷰', 'verbose_name_plural': '리뷰 목록'},
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={'verbose_name': '상점', 'verbose_name_plural': '상점 목록'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': '태그', 'verbose_name_plural': '태그 목록'},
        ),
        migrations.AddField(
            model_name='shop',
            name='photo',
            field=models.ImageField(default=1, upload_to='diary/post/%Y/%M/%d', verbose_name='업체 사진'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='author_name',
            field=models.CharField(max_length=20, verbose_name='작성자 이름'),
        ),
        migrations.AlterField(
            model_name='review',
            name='message',
            field=models.TextField(verbose_name='리뷰'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='description',
            field=models.TextField(blank=True, verbose_name='업체 설명'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='업체 명'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='tag_set',
            field=models.ManyToManyField(blank=True, to='shop.Tag', verbose_name='해시태그'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='telephone',
            field=models.CharField(help_text='입력 예) 042-1234-1234', max_length=14, validators=[django.core.validators.RegexValidator('^\\d{3}-?\\d{4}-?\\d{4}$', message='전화번호를 입력해주세요.')], verbose_name='업체 전화번호'),
        ),
        migrations.AddField(
            model_name='shop',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.category'),
            preserve_default=False,
        ),

        migrations.RunPython(create_dummy_category,delete_dummy_category)
    ]

    # 카테고리라는 이름의 모델을 만들고 makemigrations
    # 카테고리 모델 생성에 대한 migraion 파일 수셩
    # create_dummy (정방향)
    # delete_dummy (역방향)
    # operations은 항상 순서가 있음



