# Generated by Django 3.2.9 on 2021-11-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='강아지 이름')),
                ('breed', models.CharField(max_length=10, verbose_name='강아지 품종')),
                ('size', models.CharField(max_length=3, verbose_name='강아지 크기')),
                ('birthday', models.DateField(verbose_name='생일')),
                ('중성화X', models.NullBooleanField(verbose_name='중성화O')),
                ('weight', models.FloatField(max_length=100, verbose_name='몸무게')),
                ('sleep_time', models.DurationField()),
                ('morning_time', models.DateTimeField()),
                ('dinner_time', models.DateTimeField()),
            ],
        ),
    ]
