# Generated by Django 3.2.9 on 2021-11-29 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoona', '0002_auto_20211129_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pets',
            name='neutralOX',
            field=models.NullBooleanField(verbose_name='중성화 여부'),
        ),
        migrations.AlterField(
            model_name='pets',
            name='sleep_time',
            field=models.DateTimeField(),
        ),
    ]
