# Generated by Django 3.2.9 on 2021-11-29 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoona', '0003_auto_20211129_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pets',
            name='dinner_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='pets',
            name='morning_time',
            field=models.TimeField(),
        ),
    ]
