# Generated by Django 3.2.9 on 2021-11-29 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoona', '0004_auto_20211129_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='pets',
            name='character_of_pets',
            field=models.TextField(blank=True, null=True, verbose_name='강아지 성격'),
        ),
        migrations.AlterField(
            model_name='pets',
            name='dinner_time',
            field=models.TimeField(blank=True, null=True, verbose_name='저녁밥 먹는 시간'),
        ),
        migrations.AlterField(
            model_name='pets',
            name='morning_time',
            field=models.TimeField(blank=True, null=True, verbose_name='아침밥 먹는 시간'),
        ),
        migrations.AlterField(
            model_name='pets',
            name='sleep_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='자는 시간'),
        ),
    ]
