# Generated by Django 3.2.9 on 2021-11-29 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoona', '0005_auto_20211129_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pets',
            name='sleep_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='잠자는 시간'),
        ),
    ]
