# Generated by Django 3.2.9 on 2021-11-29 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoona', '0006_alter_pets_sleep_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pets',
            name='sleep_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='자는 시간'),
        ),
    ]
