# Generated by Django 3.2.9 on 2021-11-29 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoona', '0007_alter_pets_sleep_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pets',
            name='birthday',
            field=models.DateField(verbose_name='강아지 생일'),
        ),
    ]
