# Generated by Django 3.2.9 on 2021-11-29 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoona', '0008_alter_pets_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pets',
            name='birthday',
            field=models.DateField(verbose_name='강쥐 생일'),
        ),
    ]
