# Generated by Django 3.2.10 on 2021-12-17 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': '카테고리', 'verbose_name_plural': '카테고리 목록'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-id'], 'verbose_name': '리뷰', 'verbose_name_plural': '리뷰 목록'},
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={'ordering': ['-id'], 'verbose_name': '상점', 'verbose_name_plural': '상점 목록'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name'], 'verbose_name': '태그', 'verbose_name_plural': '태그 목록'},
        ),
    ]
